# Generated by Django 5.1.7 on 2025-03-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageSrc',
            field=models.ImageField(blank=True, default=None, upload_to='posts'),
        ),
    ]
