# Generated by Django 5.1.6 on 2025-03-05 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
